clc;
clear all;
close all;
format long;
rp = input('Enter the passband ripple (dB): ');
rs = input('Enter the stopband ripple (dB): ');
wp = input('Enter passband frequencies [wp1 wp2]: ');
ws = input('Enter stopband frequencies [ws1 ws2]: ');
[n,wn] = buttord(wp,ws,rp,rs,'s');
[b,a] = butter(n,wn,'stop','s');
w = logspace(1,5,1000);
[h,w] = freqs(b,a,w);
m = 20*log10(abs(h));
an = angle(h);
subplot(2,1,1);
semilogx(w,m);
grid on;
xlabel('Frequency (rad/s)');
ylabel('Magnitude (dB)');
title('Butterworth Analog Bandstop Filter');
subplot(2,1,2);
semilogx(w,an);
grid on;
xlabel('Frequency (rad/s)');
ylabel('Phase (radians)');