clc;
close all;
clear all;
format long;
rp=input('Enter the passband ripple:');
rs=input('Enter the stopband ripple: ');
wp=input('Enter the passband freq: ');
ws=input('Enter the stopband freq: ');
fs=input('Enter the sampling freq: ');
w1=2*wp/fs;
w2=2*ws/fs;
[n]=buttord(w1,w2,rp,rs);
wn=[w1 w2];
[b,a]=butter(n,wn,'bandpass','s');
w=0:.01:pi;
[h,om]=freqz(b,a,w);
m=20*log10(abs(h));
an=angle(h);
subplot(2,1,1);
plot(om/pi,m);
ylabel('Gain in dB --.');
xlabel('(a) Normalised frequency --.');
subplot(2,1,2);
plot(om/pi,an);
xlabel('(b) Normalised frequency --.');
ylabel('Phase in radians --.');
